"""
An injury case represents the clinical event that initiates a course of
physiotherapy.  One patient may have multiple injury records over time
(e.g. an ankle sprain followed later by a shoulder injury).
"""

from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.patient import PatientProfile
    from app.models.plan import ExercisePlan


class InjuryStatus(str, enum.Enum):
    ACTIVE = "active"
    RESOLVED = "resolved"
    ON_HOLD = "on_hold"


class BodyPart(str, enum.Enum):
    ANKLE = "ankle"
    KNEE = "knee"
    HIP = "hip"
    LOWER_BACK = "lower_back"
    UPPER_BACK = "upper_back"
    SHOULDER = "shoulder"
    ELBOW = "elbow"
    WRIST = "wrist"
    NECK = "neck"
    OTHER = "other"


class Injury(BaseModel):
    __tablename__ = "injuries"

    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patient_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Clinical details ───────────────────────────────────────────────────────
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Free-text description entered by the patient at intake.",
    )
    body_part: Mapped[BodyPart] = mapped_column(
        Enum(BodyPart, name="body_part"),
        nullable=False,
        index=True,
    )
    pain_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Self-reported pain intensity 1–10 at time of intake.",
    )
    status: Mapped[InjuryStatus] = mapped_column(
        Enum(InjuryStatus, name="injury_status"),
        nullable=False,
        default=InjuryStatus.ACTIVE,
        index=True,
    )

    # ── Intake media ───────────────────────────────────────────────────────────
    intake_video_s3_key: Mapped[str | None] = mapped_column(
        String(1024),
        nullable=True,
        comment="S3 object key for the intake assessment video uploaded by the patient.",
    )
    mobility_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment=(
            "Plain-language mobility summary generated by video_intake_analyzer "
            "after processing the intake video.  Fed into the initial plan prompt."
        ),
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    patient: Mapped[PatientProfile] = relationship(
        "PatientProfile",
        back_populates="injuries",
    )
    plans: Mapped[list[ExercisePlan]] = relationship(
        "ExercisePlan",
        back_populates="injury",
        cascade="all, delete-orphan",
    )