"""
Patient profile — one-to-one with User.
Stores demographic data, baseline range-of-motion measurements captured from
the intake video, and the FK to the patient's currently active plan.
"""

from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import Date, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.clinician import ClinicianProfile
    from app.models.injury import Injury
    from app.models.media import MediaFile
    from app.models.plan import ExercisePlan
    from app.models.session import ExerciseSession
    from app.models.user import User


class ActivityLevel(str, enum.Enum):
    SEDENTARY = "sedentary"
    LIGHTLY_ACTIVE = "lightly_active"
    MODERATELY_ACTIVE = "moderately_active"
    VERY_ACTIVE = "very_active"


class PatientProfile(BaseModel):
    __tablename__ = "patient_profiles"

    # ── Identity ───────────────────────────────────────────────────────────────
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )
    date_of_birth: Mapped[Any | None] = mapped_column(Date, nullable=True)
    gender: Mapped[str | None] = mapped_column(String(32), nullable=True)
    region: Mapped[str | None] = mapped_column(
        String(128),
        nullable=True,
        comment="Geographic region tag for accessibility analytics.",
    )
    activity_level: Mapped[ActivityLevel | None] = mapped_column(
        Enum(ActivityLevel, name="activity_level"),
        nullable=True,
    )
    medical_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Free-text notes entered by a clinician (not patient-visible by default).",
    )

    # ── Baseline mobility ─────────────────────────────────────────────────────
    baseline_rom: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment=(
            "Range-of-motion baseline extracted from intake video by "
            "video_intake_analyzer service. "
            "Schema: {joint_name: {angle_deg: float, timestamp: iso_str}}"
        ),
    )
    mobility_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Plain-language summary of baseline mobility generated by intake video analysis.",
    )

    # ── Active plan pointer ────────────────────────────────────────────────────
    active_plan_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("exercise_plans.id", ondelete="SET NULL", use_alter=True),
        nullable=True,
        index=True,
        comment="FK to the patient's current active ExercisePlan.",
    )

    # ── Clinician assignment ───────────────────────────────────────────────────
    assigned_clinician_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clinician_profiles.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Push notification token ────────────────────────────────────────────────
    fcm_token: Mapped[str | None] = mapped_column(
        String(512),
        nullable=True,
        comment="Firebase Cloud Messaging token for Android push notifications.",
    )
    web_push_subscription: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Web Push API subscription object for browser notifications.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    user: Mapped[User] = relationship(
        "User",
        back_populates="patient_profile",
    )
    assigned_clinician: Mapped[ClinicianProfile | None] = relationship(
        "ClinicianProfile",
        back_populates="assigned_patients",
        foreign_keys=[assigned_clinician_id],
    )
    injuries: Mapped[list[Injury]] = relationship(
        "Injury",
        back_populates="patient",
        cascade="all, delete-orphan",
        order_by="Injury.created_at.desc()",
    )
    plans: Mapped[list[ExercisePlan]] = relationship(
        "ExercisePlan",
        back_populates="patient",
        cascade="all, delete-orphan",
        foreign_keys="ExercisePlan.patient_id",
        order_by="ExercisePlan.created_at.desc()",
    )
    sessions: Mapped[list[ExerciseSession]] = relationship(
        "ExerciseSession",
        back_populates="patient",
        cascade="all, delete-orphan",
        order_by="ExerciseSession.started_at.desc()",
    )
    media_files: Mapped[list[MediaFile]] = relationship(
        "MediaFile",
        back_populates="patient",
        cascade="all, delete-orphan",
    )

    # ── Computed helpers ───────────────────────────────────────────────────────
    @property
    def age(self) -> int | None:
        """Return patient's current age in years, or None if DOB not set."""
        if self.date_of_birth is None:
            return None
        from datetime import date
        today = date.today()
        dob = self.date_of_birth
        return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))